version: '3.8'

services:
  healthcare-app:
    build: .
    image: health-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_URL="mongodb+srv://fatimaumer107:5e4ZzPFmupQxsJfj@cluster0.sjhyz.mongodb.net/healthcare?retryWrites=true&w=majority&appName=Cluster0"

      