version: '3.8'

services:
  healthcare-app:
    build: .
    container_name: healthcare_app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
